version: '3.8'

services:

  server:
    image: "go8/server"
    container_name: "go8_container"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}

  postgres:
    image: "postgres:15.4"
    restart: always
    container_name: "go8_postgres"
    healthcheck:
      test: pg_isready -U ${DB_USER}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    expose:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./scripts/create-db.sh:/docker-entrypoint-initdb.d

  redis:
    image: 'redis:7.2'
    restart: always
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes


volumes:
  postgres:
