# cd <project-root>
# docker-compose -f e2e/docker-compose.yml up --build -d

version: '3.4'

services:

  postgres:
    image: "postgres:15.1"
    container_name: "go8_postgres_e2e"
    restart: "no"
    healthcheck:
      test: pg_isready -U ${DB_USER}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
#    ports:
#      - "5435:5432" # Not strictly needed unless for debugging

  server:
    image: "go8/server_test"
    container_name: "go8_server_e2e"
    restart: "no"
    build:
      context: ../
      dockerfile: e2e/server.Dockerfile
    entrypoint: ["/usr/local/bin/server"]
    healthcheck:
      test: curl --fail http://localhost:${API_PORT}/api/health/readiness || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
#    ports:
#      - ${API_PORT}:${API_PORT} # enable for debugging
    depends_on:
      - postgres

  migrate:
    image: "go8/migrate"
    container_name: "go8_migrate_e2e"
    restart: "no"
    build:
      context: ../
      dockerfile: e2e/migrate.Dockerfile
    entrypoint: ["/usr/local/bin/migrate"]
    depends_on:
      - postgres
      - server

  e2e:
    image: "go8/e2e"
    container_name: "go8_e2e_test"
    restart: "no"
    build:
      context: ../
      dockerfile: e2e/e2e.Dockerfile
    entrypoint: ["/usr/local/bin/end_to_end"]
    depends_on:
      - postgres
      - server
      - migrate
